=== L0veRamen/ptidej-Ptidej/PADL Creator XMI/lib/SDMetricsOpenCore/src/com/sdmetrics/resources/metrics.dtd
<!ELEMENT sdmetrics (metric|set|matrix|rule|wordlist|reference|term|
        metricprocedure|setprocedure|ruleprocedure)+ >
        <!ATTLIST sdmetrics
                version CDATA #REQUIRED
                ruleexemption CDATA #IMPLIED
                exemptiontag CDATA #IMPLIED
                exemptionvalue CDATA #IMPLIED
                inheritable (true|false) "false">

        <!ELEMENT metric (description?,(projection|setoperation|compoundmetric|
                attributevalue|nesting|signature|connectedcomponents|count|compare|
                subelements|filtervalue|substring)) >
        <!ATTLIST metric
                name CDATA #REQUIRED
                domain CDATA #REQUIRED
                inheritable (true|false) "false"
                category CDATA #IMPLIED
                internal (true|false) "false">

        <!ELEMENT set (description?,(projection|compoundset|subelements|compare))>
        <!ATTLIST set
                name CDATA #REQUIRED
                domain CDATA #REQUIRED
                inheritable (true|false) "false"
                multiset (true|false) "false">


        <!ELEMENT matrix (description?,(projection|setoperation|compoundset))>
        <!ATTLIST matrix
                name CDATA #REQUIRED
                from_row_type CDATA #REQUIRED
                to_col_type CDATA #REQUIRED
                row_condition CDATA #IMPLIED
                col_condition CDATA #IMPLIED>

        <!ELEMENT rule (description?,(violation|cycle|projection|compoundset|
                valueset|compare))>
        <!ATTLIST rule
                name CDATA #REQUIRED
                domain CDATA #REQUIRED
                inheritable (true|false) "false"
                category CDATA #IMPLIED
                severity CDATA #IMPLIED
                applies_to CDATA #IMPLIED
                disabled (true|false) "false">

        <!ELEMENT wordlist (entry*)>
        <!ATTLIST wordlist
                name CDATA #REQUIRED
                ignorecase (true|false) "false">

        <!ELEMENT entry EMPTY>
        <!ATTLIST entry
                word CDATA #REQUIRED>

        <!ELEMENT description (#PCDATA)>

        <!ENTITY % scopes "same|other|higher|lower|sameorhigher|sameorlower|samebranch|
	notsamebranch|containedin|notcontainedin|idem|notidem" >

        <!ENTITY % filteratts
                'target CDATA #IMPLIED
	targetcondition CDATA #IMPLIED
	element CDATA #IMPLIED
	eltype CDATA #IMPLIED
	scope (%scopes;) #IMPLIED
	condition CDATA #IMPLIED'
                >

        <!ENTITY % sumatts
                'sum CDATA #IMPLIED
	stat (sum|min|max) "sum"'
                >

        <!ENTITY % ruleatts
                'precondition CDATA #IMPLIED
	mincnt CDATA #IMPLIED
	value CDATA #IMPLIED'
                >

        <!ELEMENT projection EMPTY>
        <!ATTLIST projection
                relation CDATA #IMPLIED
                relset CDATA #IMPLIED
                %sumatts;
                set CDATA #IMPLIED
                valueset CDATA #IMPLIED
                exclude_self (true|false) "false"
                recurse (true|false) "false"
                nesting (true|false) "false"
                %ruleatts;
                %filteratts;>

        <!ELEMENT compoundmetric EMPTY>
        <!ATTLIST compoundmetric
                term CDATA #IMPLIED
                condition CDATA #IMPLIED
                alt CDATA #IMPLIED
                fallback CDATA #IMPLIED>

        <!ELEMENT attributevalue EMPTY>
        <!ATTLIST attributevalue
                attr CDATA #REQUIRED
                element CDATA #IMPLIED>

        <!ELEMENT signature EMPTY>
        <!ATTLIST signature
                set CDATA #REQUIRED
                name CDATA #IMPLIED
                prologue CDATA #IMPLIED
                value CDATA #IMPLIED
                separator CDATA #IMPLIED
                epilogue CDATA #IMPLIED
                %filteratts;>

        <!ELEMENT connectedcomponents EMPTY>
        <!ATTLIST connectedcomponents
                set CDATA #REQUIRED
                nodes CDATA #REQUIRED>

        <!ELEMENT valuesetcount EMPTY>
        <!ATTLIST valuesetcount
                set CDATA #REQUIRED>

        <!ELEMENT count EMPTY>
        <!ATTLIST count
                term CDATA #REQUIRED
                set CDATA #REQUIRED
                relset CDATA #REQUIRED
                %filteratts;>

        <!ELEMENT compare EMPTY>
        <!ATTLIST compare
                term CDATA #IMPLIED
                set CDATA #IMPLIED
                with CDATA #IMPLIED
                comp CDATA #IMPLIED
                return_element (true|false) "false"
                exclude_self (true|false) "true"
                %ruleatts;
                %filteratts;>

        <!ELEMENT setoperation EMPTY>
        <!ATTLIST setoperation
                set CDATA #REQUIRED
                %sumatts;
                %filteratts;>

        <!ELEMENT nesting EMPTY>
        <!ATTLIST nesting
                relation CDATA #REQUIRED>

        <!ELEMENT subelements EMPTY>
        <!ATTLIST subelements
                set CDATA #IMPLIED
                exclude_self (true|false) "true"
                valueset CDATA #IMPLIED
                %filteratts;
                %sumatts;>

        <!ELEMENT filtervalue EMPTY>
        <!ATTLIST filtervalue
                relation CDATA #IMPLIED
                relset CDATA #IMPLIED
                value CDATA #IMPLIED
                %filteratts;>

        <!ELEMENT substring EMPTY>
        <!ATTLIST substring
                source CDATA #REQUIRED
                separator CDATA #REQUIRED
                position CDATA #IMPLIED
                endseparator CDATA #IMPLIED
                limit CDATA #IMPLIED
                result CDATA #IMPLIED>

        <!ELEMENT compoundset EMPTY>
        <!ATTLIST compoundset
                set CDATA #REQUIRED
                cum CDATA #IMPLIED
                valueset CDATA #IMPLIED
                exclude_self (true|false) "false"
                %ruleatts;
                %filteratts;>

        <!ELEMENT violation EMPTY>
        <!ATTLIST violation
                condition CDATA #REQUIRED
                value CDATA #IMPLIED>

        <!ELEMENT valueset EMPTY>
        <!ATTLIST valueset
                set CDATA #REQUIRED
                precondition CDATA #IMPLIED
                mincnt CDATA #IMPLIED>

        <!ELEMENT cycle EMPTY>
        <!ATTLIST cycle
                nodes CDATA #REQUIRED
                minnodes CDATA #IMPLIED>

        <!ELEMENT reference (#PCDATA|description)*>
        <!ATTLIST reference
                tag CDATA #REQUIRED>

        <!ELEMENT term (#PCDATA|description)*>
        <!ATTLIST term
                name CDATA #REQUIRED>

        <!ELEMENT metricprocedure EMPTY>
        <!ATTLIST metricprocedure
                name CDATA #REQUIRED
                class CDATA #REQUIRED>
        <!ELEMENT setprocedure EMPTY>
        <!ATTLIST setprocedure
                name CDATA #REQUIRED
                class CDATA #REQUIRED>

        <!ELEMENT ruleprocedure EMPTY>
        <!ATTLIST ruleprocedure
                name CDATA #REQUIRED
                class CDATA #REQUIRED>

=== L0veRamen/ptidej-Ptidej/PADL Creator XMI/lib/SDMetricsOpenCore/src/com/sdmetrics/resources/metrics.xml
<?xml version="1.0"?>
<!DOCTYPE sdmetrics SYSTEM 'metrics.dtd'>

<!-- metrics.xml

SDMetrics V2.2 metric definitions for the UML1.x default metamodel
Copyright (c) 2002-2013 Juergen Wuest

The MIT License

Permission is hereby granted, free of charge, to any person obtaining a copy
of this SDMetrics project file (the "Project File"), to deal in the Project File 
without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Project File, and to permit persons to whom the Project File is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Project File.

THE PROJECT FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE PROJECT FILE.

Note: this license grant only applies to this Project File, and not to any
other part of SDMetrics.

-->

<sdmetrics version="2.0" ruleexemption="taggedvalue" exemptiontag="tagname">


    <!-- class metrics -->
    <!-- class size -->

    <metric name="NumAttr" domain="class" category="Size">
        <description>The number of attributes in the class.((p))
            This metric counts all attributes regardless of their type (data type,
            class or interface), visibility, changeability (read only
            or not), and owner scope (class-scope, i.e. static, or instance
            attribute). Inherited attributes are not counted.
            ((ul))((li))Also known as: NV (Number of Variables per class)
            ref://LK94/.((/ul))
        </description>
        <projection relation="context" target="attribute"/>
    </metric>

    <metric name="NumOps" domain="class" category="Size">
        <description>The number of operations in a class.((p))
            Includes all operations in the class that are explicitly modeled
            (overriding operations, constructors, destructors), regardless
            of their visibility, owner scope (class-scope, i.e., static),
            or whether they are abstract or not. Inherited operations are
            not counted.
            ((ul))
            ((li))Also known as: WMC (Weighted method complexity) where each operation is
            assigned unity complexity ref://CK94/.
            ((li))Also known as: NM (Number of Methods) ref://LK94/.
            ((/ul))
        </description>
        <projection relation="context" target="operation"/>
    </metric>

    <metric name="NumPubOps" domain="class" category="Size">
        <description>The number of public operations in a class.((p))
            Same as metric metric://class/NumOps/, but only counts operations with
            public visibility. Measures the size of the class in terms
            of its public interface.
            ((ul))((li))Also known as: NPM (Number of Public Methods)
            ref://LK94/.((/ul))
        </description>
        <projection relation="context" target="operation" condition="visibility='public'"/>
    </metric>

    <metric name="Setters" domain="class" category="Size">
        <description>The number of operations with a name starting with 'set'.((p))
            Note that this metric does not always yield accurate results. For example, an
            operation ((code))settleAccount((/code)) will be counted as setter method.
            ((ul))((li))See also: metric://class/Getters/.((/ul))
        </description>
        <projection relation="context" target="operation" condition="name startswith 'set'"/>
    </metric>

    <metric name="Getters" domain="class" category="Size">
        <description>The number of operations with a name starting with 'get', 'is', or
            'has'.((p))
            Note that this metric does not always yield accurate results. For example, an
            operation ((code))isolateNode((/code)) will be counted as getter method.
            ((ul))((li))See also: metric://class/Setters/.((/ul))
        </description>
        <projection relation="context" target="operation" sum="GetterName"/>
    </metric>

    <!-- class nesting structure -->
    <metric name="Nesting" domain="class">
        <description>The nesting level of the class (for inner classes).((p))
            Measures how deeply a class is nested within other classes.
            Classes not defined in the context of another class have nesting level 0,
            their inner classes have nesting level 1, etc.
            Nesting levels deeper than 1 are unusual; an excessive nesting structure
            is difficult to understand, and should be revised.
        </description>
        <nesting relation="context"/>
    </metric>


    <!-- class inheritance -->

    <set name="ImplInterfaces" domain="class">
        <description>The set of interfaces the class implements.</description>
        <projection relation="absclient" target="abstraction" element="abssupplier"/>
    </set>

    <metric name="IFImpl" domain="class" category="Inheritance">
        <description>The number of interfaces the class implements (UML Abstraction).((p))
            This only counts direct relationships from the class to the interface. For
            example, if a class ((i))C((/i)) implements an interface ((i))I((/i)),
            which extends some other interfaces, only interface ((i))I((/i))
            will be counted, but not the interfaces that ((i))I((/i)) extends
            (even though class ((i))c((/i)) implements those interfaces, too).
        </description>
        <compoundmetric term="size(ImplInterfaces)"/>
    </metric>

    <metric name="NOC" domain="class" category="Inheritance">
        <description>The number of children of the class (UML Generalization).((p))
            Similar to glossary://Coupling (export)/export coupling/, NOC indicates the
            potential influence a class has on the design.
            If a class has a large number of children, it may require more testing of the
            methods in that class. A large number of child classes may indicate improper
            abstraction of the parent class.
            ((ul))((li))Defined in ref://CK94/.((/ul))
        </description>
        <projection relation="genparent" target="generalization" element="genchild"/>
    </metric>

    <metric name="NumDesc" domain="class" category="Inheritance">
        <description>The number of descendents of the class (UML Generalization).((p))
            Counts the number of children of the class, their children, and so on.
            ((ul))
            ((li))See also: metric://class/NOC/ (Number of Children).
            ((li))Suggested in ref://LC94/ and ref://TSM92/.
            ((/ul))
        </description>
        <compoundmetric term="size(DescSet)"/>
    </metric>

    <metric name="NumAnc" domain="class" category="Inheritance">
        <description>The number of ancestors of the class.((p))
            Counts the number of parents of the class, their parents, and so on.
            If multiple inheritance is not used, the metric yields the same
            values as metric://class/DIT/.
            ((ul))((li))Suggested in ref://LC94/ and ref://TSM92/.((/ul))
        </description>
        <compoundmetric term="size(AncSet)"/>
    </metric>

    <metric name="DIT" domain="class" category="Inheritance">
        <description>The depth of the class in the inheritance hierarchy.((p))
            This is calculated as the longest path from the class to the root of
            the inheritance tree. The DIT for a class that has no parents is 0.((p))
            Classes with high DIT inherit from many classes and thus are more
            difficult to understand. Also, classes with high DIT may not be proper
            specializations of all of their ancestor classes.
            ((ul))((li))Defined in ref://CK94/.((/ul))
        </description>
        <projection relation="genchild" target="generalization" element="genparent" eltype="class" nesting="true"/>
    </metric>

    <metric name="CLD" domain="class" category="Inheritance">
        <description>Class to leaf depth. The longest path from the class to a leaf
            node in the inheritance hierarchy below the class.
            ((ul))((li))Defined in ref://TSM92/.
            ((li))See also: metric://class/NOC/ (Number of Children).((/ul))
        </description>
        <projection relation="genparent" target="generalization" element="genchild" eltype="class" nesting="true"/>
    </metric>

    <set name="Parents" domain="class">
        <description>The set of parents of the class.</description>
        <projection relation="genchild" target="generalization" element="genparent" eltype="class"/>
    </set>

    <set name="Children" domain="class">
        <description>The set of child classes of the class.</description>
        <projection relation="genparent" target="generalization" element="genchild" eltype="class"/>
    </set>

    <set name="AncSet" domain="class">
        <description>The set of ancestors of the class.</description>
        <projection relation="genchild" target="generalization" element="genparent" eltype="class" recurse="true"/>
    </set>

    <set name="DescSet" domain="class">
        <description>The set of descendents of the class.</description>
        <projection relation="genparent" target="generalization" element="genchild" eltype="class" recurse="true"/>
    </set>

    <metric name="OpsInh" domain="class" category="Inheritance">
        <description>The number of inherited operations.((p))
